language: ruby

services:
    - docker

before_install:
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

before_script:
    - rm web/app_dev.php web/config.php

script:
    - docker build -f Dockerfile.remote -t sskorc/tidy-compass-dist .

deploy:
  provider: script
  script: ./deploy.sh
  skip_cleanup: true
  on:
    branch: master
